language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- pypy
- pypy3
install: pip install . --use-mirrors
script: python setup.py nosetests
deploy:
  provider: pypi
  user: github-ll
  password:
    secure: DPz0VuHjZp/586ImakwtjqQzEIq6crQLMv1/Z4OKD1C1XY/KQ7uEgYTGSEDR4e2m5K8id3ZXkAEQSuopyrQ0on6KuwTmfT9U7dsk3ijCkHc2XSwfC5uU7eWgrbn62wVWo3kchBerAWOvOmXiXBdTiIOIfJ7MvvxcfAkz/1zRYx8=
  on:
    tags: true
    repo: locationlabs/mockredis
