language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- pypy
- pypy3
install: pip install . --use-mirrors
script: python setup.py nosetests
deploy:
  provider: pypi
  user: github-ll
  password:
    secure: a64VGzyBWpg9qNv6NnURDwuDxDKYeIvWnfjTctM+BgNurPfbJ9ohYiCbJIEGR9KnA4el3RPNe8AiaOJhiP7xo2x4fqvT2HRWHnarl6jpgz0Fe+0LOcop8sknxz5ePDSFZSaQYpIWJTGkDaBBHMtt7CMNr3UbV7G/HT8hyl5r69Y=
  on:
    tags: true
    repo: locationlabs/mockredis
