language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- pypy
- pypy3
install: pip install . --use-mirrors
script: python setup.py nosetests
deploy:
  provider: pypi
  user: github-ll
  password:
    secure: Ol3Gxz2iQEh7Oz64FZJfwLJK/r8QLlnE3aFKv6TkTxn8DedXK+mLUTC0PwueBSOIRGpnxlHwQyzrzxZWs2QOUoyB+Nbx6L1wU+NsgviNKJjAln4/tV4dAeI7GRJD2cDkRH9w2QihWnRFRh7BbmhfsD4WrsELP5k6onbVrQwU/Ao=
  on:
    tags: true
    repo: locationlabs/mockredis
